name: "Deploy Frank the POSsim"

on:
  push:
    branches:
      - release
env:
  PROJECT_PATH: FrankThePOSsim/FrankThePOSsim.csproj
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Run dotnet publish no self-contained
        run: dotnet publish ${{ env.PROJECT_PATH }} -o nsc -c Release --no-self-contained -r win-x64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:CopyLocalLockFileAssemblies=false

      - name: Run dotnet publish self-contained
        run: dotnet publish ${{ env.PROJECT_PATH }} -o sc -c Release --self-contained -r win-x64 -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:CopyLocalLockFileAssemblies=false

      - name: Rename self-contained file
        run: Rename-Item -Path "sc/FrankThePOSsim.exe" -NewName "FrankThePOSsim-self-contained.exe"
  
      - name: Create the release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            nsc/appsettings.json
            nsc/FrankThePOSsim.exe
            sc/FrankThePOSsim-self-contained.exe
